- docker-compose -f docker-compose-build.yaml build --parallel

docker tag udagram-api-feed ypapy/udagram-api-feed:v1
docker tag udagram-api-feed ypapy/udagram-api-user:v1
docker tag udagram-api-feed ypapy/udagram-frontend:v1
docker tag udagram-api-feed ypapy/udagram-reverseproxy:v1

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push ypapy/udagram-api-feed:v1
- docker push ypapy/udagram-api-user:v1
- docker push ypapy/udagram-frontend:v1
- docker push ypapy/udagram-reverseproxy:v1
