language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed:latest
  - docker tag udagram-api-user "$DOCKER_USERNAME"/udagram-api-user:latest
  - docker tag udagram-frontend "$DOCKER_USERNAME"/udagram-frontend:latest
  - docker tag udagram-reverseproxy "$DOCKER_USERNAME"/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/udagram-api-feed:latest
  - docker push "$DOCKER_USERNAME"/udagram-api-user:latest
  - docker push "$DOCKER_USERNAME"/udagram-frontend:latest
  - docker push "$DOCKER_USERNAME"/udagram-reverseproxy:latest
