apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - image: ypapy/udagram-api-feed:latest
        imagePullPolicy: Always
        name: udagram-api-feed
        ports:
        - containerPort: 8080
          protocol: TCP